1260047 + 0 in total (QC-passed reads + QC-failed reads)
222635 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
342631 + 0 mapped (27.19%:-nan%)
1037412 + 0 paired in sequencing
518706 + 0 read1
518706 + 0 read2
86698 + 0 properly paired (8.36%:-nan%)
93606 + 0 with itself and mate mapped
26390 + 0 singletons (2.54%:-nan%)
6 + 0 with mate mapped to a different chr
4 + 0 with mate mapped to a different chr (mapQ>=5)
