1037412 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
85367 + 0 mapped (8.23%:-nan%)
1037412 + 0 paired in sequencing
518706 + 0 read1
518706 + 0 read2
69328 + 0 properly paired (6.68%:-nan%)
73921 + 0 with itself and mate mapped
11446 + 0 singletons (1.10%:-nan%)
3 + 0 with mate mapped to a different chr
3 + 0 with mate mapped to a different chr (mapQ>=5)
